# Generated by Django 3.0.7 on 2020-07-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
