# Generated by Django 3.0.7 on 2020-07-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
